name: Nightly Documentation Build

on:
  workflow_dispatch:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * *'

env:
  DOCUMENTATION_CNAME: 'aedt.docs.pyansys.com'
  MAIN_PYTHON_VERSION: '3.10'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc-build:
    name: "Build project documentation"
    runs-on: ubuntu-latest
    needs: doc-style
    steps:
      - name: "Building project documentation"
        uses: pyansys/actions/doc-build@v3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc_upload:
    needs: doc_build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy development documentation
        uses: pyansys/actions/doc-deploy-dev@v3
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          requires-xvfb: true
